-- NexaPlay AI Batch 4: application-owned user state.
-- Additive integration only; catalog, character, embedding, and recommendation
-- structures from earlier batches remain unchanged.

begin;

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text,
  avatar_url text,
  favorite_genres jsonb not null default '[]'::jsonb,
  favorite_types jsonb not null default '[]'::jsonb,
  favorite_moods jsonb not null default '[]'::jsonb,
  onboarding_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint user_profiles_username_not_blank check (
    username is null or btrim(username) <> ''
  ),
  constraint user_profiles_favorite_genres_array check (
    jsonb_typeof(favorite_genres) = 'array'
  ),
  constraint user_profiles_favorite_types_array check (
    jsonb_typeof(favorite_types) = 'array'
  ),
  constraint user_profiles_favorite_moods_array check (
    jsonb_typeof(favorite_moods) = 'array'
  )
);

create table if not exists public.watchlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id bigint not null references public.contents(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint watchlists_user_content_key unique (user_id, content_id)
);

create table if not exists public.watch_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id bigint not null references public.contents(id) on delete cascade,
  progress numeric(5, 2) not null default 0,
  status text not null default 'watching',
  started_at timestamptz not null default now(),
  watched_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint watch_history_user_content_key unique (user_id, content_id),
  constraint watch_history_progress_range check (progress between 0 and 100),
  constraint watch_history_status_allowed check (
    status in ('watching', 'completed', 'dropped')
  )
);

comment on table public.user_profiles is
  'Supabase Auth profile and onboarding preferences used by the Batch 4 application.';
comment on table public.watchlists is
  'User-owned saved entertainment items with one row per user and content.';
comment on table public.watch_history is
  'User-owned viewing progress used by Continue Watching and recommendation signals.';
comment on column public.user_profiles.favorite_genres is 'JSON array selected during onboarding.';
comment on column public.user_profiles.favorite_types is 'JSON array containing movie, anime, or series preferences.';
comment on column public.user_profiles.favorite_moods is 'JSON array of tone preferences such as dark or relaxing.';
comment on column public.watch_history.progress is 'Viewing completion percentage from 0 through 100.';

create index if not exists watchlists_user_created_idx
  on public.watchlists (user_id, created_at desc);
create index if not exists watchlists_content_idx
  on public.watchlists (content_id);
create index if not exists watch_history_user_updated_idx
  on public.watch_history (user_id, updated_at desc);
create index if not exists watch_history_continue_idx
  on public.watch_history (user_id, status, progress desc);

create or replace function public.set_application_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists user_profiles_set_updated_at on public.user_profiles;
create trigger user_profiles_set_updated_at
before update on public.user_profiles
for each row execute function public.set_application_updated_at();

drop trigger if exists watch_history_set_updated_at on public.watch_history;
create trigger watch_history_set_updated_at
before update on public.watch_history
for each row execute function public.set_application_updated_at();

create or replace function public.create_profile_for_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.user_profiles (id, username, avatar_url)
  values (
    new.id,
    nullif(coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)), ''),
    nullif(new.raw_user_meta_data ->> 'avatar_url', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists auth_user_created_profile on auth.users;
create trigger auth_user_created_profile
after insert on auth.users
for each row execute function public.create_profile_for_new_user();

-- Extend the existing Batch 3 event stream without replacing its table.
alter table public.user_interactions
  drop constraint if exists user_interactions_type_allowed,
  drop constraint if exists user_interactions_content_consistent;

alter table public.user_interactions
  add constraint user_interactions_type_allowed check (
    interaction_type in (
      'view', 'click', 'like', 'watchlist', 'complete', 'rating', 'search', 'chat'
    )
  ),
  add constraint user_interactions_content_consistent check (
    content_id is not null or interaction_type in ('search', 'chat')
  );

alter table public.user_profiles enable row level security;
alter table public.watchlists enable row level security;
alter table public.watch_history enable row level security;

create policy user_profiles_select_own on public.user_profiles
for select to authenticated using ((select auth.uid()) = id);
create policy user_profiles_insert_own on public.user_profiles
for insert to authenticated with check ((select auth.uid()) = id);
create policy user_profiles_update_own on public.user_profiles
for update to authenticated
using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy watchlists_select_own on public.watchlists
for select to authenticated using ((select auth.uid()) = user_id);
create policy watchlists_insert_own on public.watchlists
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy watchlists_delete_own on public.watchlists
for delete to authenticated using ((select auth.uid()) = user_id);

create policy watch_history_select_own on public.watch_history
for select to authenticated using ((select auth.uid()) = user_id);
create policy watch_history_insert_own on public.watch_history
for insert to authenticated with check ((select auth.uid()) = user_id);
create policy watch_history_update_own on public.watch_history
for update to authenticated
using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy watch_history_delete_own on public.watch_history
for delete to authenticated using ((select auth.uid()) = user_id);

grant select, insert, update on table public.user_profiles to authenticated;
grant select, insert, delete on table public.watchlists to authenticated;
grant select, insert, update, delete on table public.watch_history to authenticated;
grant all on table public.user_profiles, public.watchlists, public.watch_history to service_role;
grant usage, select on sequence public.watchlists_id_seq, public.watch_history_id_seq
  to authenticated, service_role;
revoke execute on function public.set_application_updated_at() from public, anon, authenticated;
revoke execute on function public.create_profile_for_new_user() from public, anon, authenticated;

commit;
