-- EntertainmentAI unified content catalog for Supabase/PostgreSQL.
-- Embeddings use 384 dimensions to match the Sentence Transformer profile
-- used by this project. Change the dimension before applying this migration
-- if the production embedding model emits a different vector size.

begin;

create schema if not exists extensions;
create extension if not exists vector with schema extensions;
create extension if not exists pg_trgm with schema extensions;

do $$
begin
  create type public.content_type as enum (
    'movie',
    'anime',
    'kdrama',
    'tv_series',
    'documentary'
  );
exception
  when duplicate_object then null;
end
$$;

comment on type public.content_type is
  'Supported unified entertainment categories in EntertainmentAI.';

create table if not exists public.contents (
  id bigint generated by default as identity primary key,
  external_id text not null,
  source text not null,
  content_type public.content_type not null,

  title text not null,
  original_title text,
  alternative_titles jsonb not null default '[]'::jsonb,

  overview text,
  tagline text,

  genres jsonb not null default '[]'::jsonb,
  original_language varchar(16),
  country jsonb not null default '[]'::jsonb,

  release_date date,
  release_year integer,

  poster_url text,
  backdrop_url text,
  trailer_url text,

  duration_minutes integer,
  episodes integer,
  season_number integer,
  studio jsonb not null default '[]'::jsonb,
  network text,

  director jsonb not null default '[]'::jsonb,
  cast jsonb not null default '[]'::jsonb,
  characters jsonb not null default '[]'::jsonb,

  rating_average numeric(4, 2),
  rating_count integer not null default 0,
  imdb_rating numeric(4, 2),
  mal_rating numeric(4, 2),
  popularity_score numeric(12, 4) not null default 0,

  embedding extensions.vector(384),
  ai_summary text,
  ai_tags jsonb not null default '[]'::jsonb,
  themes jsonb not null default '[]'::jsonb,
  moods jsonb not null default '[]'::jsonb,

  search_document tsvector generated always as (
    setweight(to_tsvector('simple'::regconfig, coalesce(title, '')), 'A') ||
    setweight(to_tsvector('simple'::regconfig, coalesce(overview, '')), 'B') ||
    setweight(to_tsvector('simple'::regconfig, genres::text), 'B') ||
    setweight(to_tsvector('simple'::regconfig, themes::text), 'B')
  ) stored,

  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint contents_source_external_id_key unique (source, external_id),
  constraint contents_external_id_not_blank check (btrim(external_id) <> ''),
  constraint contents_source_not_blank check (btrim(source) <> ''),
  constraint contents_source_canonical_case check (source = upper(source)),
  constraint contents_title_not_blank check (btrim(title) <> ''),
  constraint contents_alternative_titles_array check (jsonb_typeof(alternative_titles) = 'array'),
  constraint contents_genres_array check (jsonb_typeof(genres) = 'array'),
  constraint contents_country_array check (jsonb_typeof(country) = 'array'),
  constraint contents_studio_array check (jsonb_typeof(studio) = 'array'),
  constraint contents_director_array check (jsonb_typeof(director) = 'array'),
  constraint contents_cast_array check (jsonb_typeof(cast) = 'array'),
  constraint contents_characters_array check (jsonb_typeof(characters) = 'array'),
  constraint contents_ai_tags_array check (jsonb_typeof(ai_tags) = 'array'),
  constraint contents_themes_array check (jsonb_typeof(themes) = 'array'),
  constraint contents_moods_array check (jsonb_typeof(moods) = 'array'),
  constraint contents_release_year_range check (release_year is null or release_year between 1800 and 2200),
  constraint contents_release_date_year_consistent check (
    release_date is null
    or release_year is null
    or release_year = extract(year from release_date)::integer
  ),
  constraint contents_duration_positive check (duration_minutes is null or duration_minutes > 0),
  constraint contents_episodes_nonnegative check (episodes is null or episodes >= 0),
  constraint contents_season_nonnegative check (season_number is null or season_number >= 0),
  constraint contents_rating_average_range check (rating_average is null or rating_average between 0 and 10),
  constraint contents_rating_count_nonnegative check (rating_count >= 0),
  constraint contents_imdb_rating_range check (imdb_rating is null or imdb_rating between 0 and 10),
  constraint contents_mal_rating_range check (mal_rating is null or mal_rating between 0 and 10),
  constraint contents_popularity_nonnegative check (popularity_score >= 0)
);

comment on table public.contents is
  'Unified metadata catalog for movies, anime, K-dramas, TV series, and documentaries used by recommendation, semantic search, and RAG.';
comment on column public.contents.id is 'Internal immutable identity generated by PostgreSQL.';
comment on column public.contents.external_id is 'Content identifier assigned by the external source API.';
comment on column public.contents.source is 'Canonical uppercase source name such as TMDB, JIKAN, or OMDB.';
comment on column public.contents.content_type is 'Normalized EntertainmentAI category.';
comment on column public.contents.title is 'Primary display and search title.';
comment on column public.contents.original_title is 'Title in the content original language.';
comment on column public.contents.alternative_titles is 'JSON array of localized, romanized, abbreviated, or alias titles.';
comment on column public.contents.overview is 'Long-form synopsis supplied by the source or editorial pipeline.';
comment on column public.contents.tagline is 'Short promotional or editorial tagline.';
comment on column public.contents.genres is 'JSON array of normalized genre strings.';
comment on column public.contents.original_language is 'BCP-47 or source language code, for example en, ja, or ko.';
comment on column public.contents.country is 'JSON array of production country names or ISO codes.';
comment on column public.contents.release_date is 'Canonical first release or premiere date.';
comment on column public.contents.release_year is 'Denormalized year for fast filtering and recommendation features.';
comment on column public.contents.poster_url is 'Portrait poster asset URL.';
comment on column public.contents.backdrop_url is 'Landscape backdrop asset URL.';
comment on column public.contents.trailer_url is 'Canonical trailer URL when available.';
comment on column public.contents.duration_minutes is 'Runtime in minutes for films, episodes, or a representative episode.';
comment on column public.contents.episodes is 'Total known episode count for episodic content.';
comment on column public.contents.season_number is 'Total known seasons or source-specific season number.';
comment on column public.contents.studio is 'JSON array of production studio objects or names.';
comment on column public.contents.network is 'Primary broadcaster, network, or streaming platform.';
comment on column public.contents.director is 'JSON array of director or creator objects.';
comment on column public.contents.cast is 'JSON array of cast objects; objects may include name, role, order, and external IDs.';
comment on column public.contents.characters is 'JSON array of character and performer or voice-actor relationships.';
comment on column public.contents.rating_average is 'Source-normalized aggregate rating on a 0 to 10 scale.';
comment on column public.contents.rating_count is 'Number of ratings behind rating_average.';
comment on column public.contents.imdb_rating is 'IMDb rating on a 0 to 10 scale when available.';
comment on column public.contents.mal_rating is 'MyAnimeList rating on a 0 to 10 scale when available.';
comment on column public.contents.popularity_score is 'Nonnegative normalized ranking feature; scale is defined by the ingestion pipeline.';
comment on column public.contents.embedding is '384-dimensional semantic embedding used by pgvector cosine search and RAG retrieval.';
comment on column public.contents.ai_summary is 'LLM-generated retrieval summary grounded in source metadata.';
comment on column public.contents.ai_tags is 'JSON array of AI-enriched entities, tropes, or retrieval labels.';
comment on column public.contents.themes is 'JSON array of normalized narrative themes.';
comment on column public.contents.moods is 'JSON array of normalized emotional or tonal labels.';
comment on column public.contents.search_document is 'Stored weighted full-text vector generated from title, overview, genres, and themes.';
comment on column public.contents.is_active is 'Soft-publication flag; inactive records remain available to trusted server processes only.';
comment on column public.contents.created_at is 'UTC-aware creation timestamp.';
comment on column public.contents.updated_at is 'UTC-aware timestamp refreshed automatically on every update.';

create index if not exists contents_content_type_idx
  on public.contents (content_type);
create index if not exists contents_title_lower_idx
  on public.contents (lower(title));
create index if not exists contents_title_trgm_idx
  on public.contents using gin (lower(title) extensions.gin_trgm_ops);
create index if not exists contents_release_year_idx
  on public.contents (release_year);
create index if not exists contents_rating_average_idx
  on public.contents (rating_average desc nulls last);
create index if not exists contents_popularity_score_idx
  on public.contents (popularity_score desc);
create index if not exists contents_search_document_idx
  on public.contents using gin (search_document);
create index if not exists contents_genres_gin_idx
  on public.contents using gin (genres jsonb_path_ops);
create index if not exists contents_themes_gin_idx
  on public.contents using gin (themes jsonb_path_ops);
create index if not exists contents_moods_gin_idx
  on public.contents using gin (moods jsonb_path_ops);
create index if not exists contents_embedding_hnsw_idx
  on public.contents using hnsw (embedding extensions.vector_cosine_ops)
  where embedding is not null;

create or replace function public.set_contents_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

comment on function public.set_contents_updated_at() is
  'Refreshes contents.updated_at before a row update.';

drop trigger if exists contents_set_updated_at on public.contents;
create trigger contents_set_updated_at
before update on public.contents
for each row
execute function public.set_contents_updated_at();

create or replace function public.match_contents(
  query_embedding extensions.vector(384),
  match_count integer default 10,
  filter_content_type public.content_type default null,
  min_similarity double precision default 0
)
returns table (
  id bigint,
  title text,
  content_type public.content_type,
  overview text,
  poster_url text,
  rating_average numeric,
  similarity double precision
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    c.id,
    c.title,
    c.content_type,
    c.overview,
    c.poster_url,
    c.rating_average,
    1 - (c.embedding <=> query_embedding) as similarity
  from public.contents as c
  where c.is_active
    and c.embedding is not null
    and (filter_content_type is null or c.content_type = filter_content_type)
    and 1 - (c.embedding <=> query_embedding) >= coalesce(min_similarity, 0)
  order by c.embedding <=> query_embedding
  limit least(greatest(coalesce(match_count, 10), 1), 100);
$$;

comment on function public.match_contents(extensions.vector, integer, public.content_type, double precision) is
  'RLS-aware cosine similarity retrieval function for semantic search and RAG.';

alter table public.contents enable row level security;

drop policy if exists contents_public_read_active on public.contents;
create policy contents_public_read_active
on public.contents
for select
to anon, authenticated
using (is_active = true);

comment on policy contents_public_read_active on public.contents is
  'Allows Supabase clients to read only active catalog records. Writes remain server-only through service_role.';

grant select on table public.contents to anon, authenticated;
revoke insert, update, delete, truncate, references, trigger
  on table public.contents from anon, authenticated;
grant all on table public.contents to service_role;
grant usage, select on sequence public.contents_id_seq to service_role;
revoke execute on function public.set_contents_updated_at() from public, anon, authenticated;
revoke execute on function public.match_contents(
  extensions.vector,
  integer,
  public.content_type,
  double precision
) from public;
grant execute on function public.match_contents(
  extensions.vector,
  integer,
  public.content_type,
  double precision
) to anon, authenticated, service_role;

-- Idempotent sample catalog records. Embeddings remain null until the
-- embedding pipeline processes each record with the configured 384-d model.
insert into public.contents (
  external_id,
  source,
  content_type,
  title,
  original_title,
  alternative_titles,
  overview,
  tagline,
  genres,
  original_language,
  country,
  release_date,
  release_year,
  poster_url,
  backdrop_url,
  trailer_url,
  duration_minutes,
  episodes,
  season_number,
  studio,
  network,
  director,
  cast,
  characters,
  rating_average,
  rating_count,
  imdb_rating,
  mal_rating,
  popularity_score,
  ai_summary,
  ai_tags,
  themes,
  moods
)
values
  (
    '157336',
    'TMDB',
    'movie',
    'Interstellar',
    'Interstellar',
    '["Interstellar"]'::jsonb,
    'A team of explorers travels through a wormhole in space to find a new home for humanity.',
    'Mankind was born on Earth. It was never meant to die here.',
    '["Adventure", "Drama", "Sci-Fi"]'::jsonb,
    'en',
    '["United States", "United Kingdom"]'::jsonb,
    '2014-11-05',
    2014,
    'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    'https://image.tmdb.org/t/p/original/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg',
    'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    169,
    null,
    null,
    '[{"name": "Legendary Pictures"}, {"name": "Syncopy"}]'::jsonb,
    null,
    '[{"name": "Christopher Nolan", "role": "Director"}]'::jsonb,
    '[{"name": "Matthew McConaughey", "character": "Cooper", "order": 0}, {"name": "Anne Hathaway", "character": "Brand", "order": 1}]'::jsonb,
    '[{"name": "Cooper", "performer": "Matthew McConaughey"}, {"name": "Brand", "performer": "Anne Hathaway"}]'::jsonb,
    8.70,
    2300000,
    8.70,
    null,
    98.4000,
    'An emotional science-fiction epic about family, time, survival, and humanity crossing the stars.',
    '["wormhole", "hard sci-fi", "father-daughter", "space"]'::jsonb,
    '["space exploration", "time dilation", "family", "human survival"]'::jsonb,
    '["emotional", "epic", "thought-provoking", "hopeful"]'::jsonb
  ),
  (
    '16498',
    'JIKAN',
    'anime',
    'Attack on Titan',
    'Shingeki no Kyojin',
    '["Shingeki no Kyojin", "AoT", "進撃の巨人"]'::jsonb,
    'Humanity fights for survival behind enormous walls while young soldiers uncover the truth about the Titans.',
    null,
    '["Action", "Drama", "Fantasy", "Suspense"]'::jsonb,
    'ja',
    '["Japan"]'::jsonb,
    '2013-04-07',
    2013,
    'https://cdn.myanimelist.net/images/anime/10/47347l.jpg',
    null,
    null,
    24,
    25,
    1,
    '[{"name": "Wit Studio"}]'::jsonb,
    'MBS',
    '[{"name": "Tetsuro Araki", "role": "Director"}]'::jsonb,
    '[{"name": "Yuki Kaji", "character": "Eren Yeager", "language": "Japanese"}, {"name": "Yui Ishikawa", "character": "Mikasa Ackerman", "language": "Japanese"}]'::jsonb,
    '[{"name": "Eren Yeager", "voice_actor": "Yuki Kaji"}, {"name": "Mikasa Ackerman", "voice_actor": "Yui Ishikawa"}]'::jsonb,
    8.60,
    3900000,
    null,
    8.60,
    99.1000,
    'A dark war fantasy about survival, freedom, inherited conflict, and the cost of breaking cycles of violence.',
    '["titans", "military", "mystery", "manga adaptation"]'::jsonb,
    '["war", "survival", "freedom", "revenge"]'::jsonb,
    '["dark", "emotional", "intense", "tragic"]'::jsonb
  ),
  (
    '126485',
    'TMDB',
    'kdrama',
    'Moving',
    '무빙',
    '["Moving", "무빙"]'::jsonb,
    'Children with hidden superpowers and their parents face a dangerous secret connected to their shared past.',
    null,
    '["Action", "Drama", "Fantasy", "Mystery"]'::jsonb,
    'ko',
    '["South Korea"]'::jsonb,
    '2023-08-09',
    2023,
    null,
    null,
    null,
    50,
    20,
    1,
    '[{"name": "Studio&NEW"}, {"name": "Mr. Romance"}]'::jsonb,
    'Disney+',
    '[{"name": "Park In-je", "role": "Director"}, {"name": "Kang Full", "role": "Writer"}]'::jsonb,
    '[{"name": "Ryu Seung-ryong", "character": "Jang Ju-won"}, {"name": "Han Hyo-joo", "character": "Lee Mi-hyun"}, {"name": "Zo In-sung", "character": "Kim Doo-sik"}]'::jsonb,
    '[{"name": "Jang Ju-won", "performer": "Ryu Seung-ryong"}, {"name": "Lee Mi-hyun", "performer": "Han Hyo-joo"}]'::jsonb,
    8.50,
    45000,
    8.40,
    null,
    92.3000,
    'A multigenerational Korean superhero drama grounded in family, sacrifice, first love, and hidden identity.',
    '["superpowers", "parents", "high school", "webtoon adaptation"]'::jsonb,
    '["family", "sacrifice", "coming of age", "hidden identity"]'::jsonb,
    '["emotional", "suspenseful", "heartwarming", "intense"]'::jsonb
  )
on conflict (source, external_id) do update
set
  content_type = excluded.content_type,
  title = excluded.title,
  original_title = excluded.original_title,
  alternative_titles = excluded.alternative_titles,
  overview = excluded.overview,
  tagline = excluded.tagline,
  genres = excluded.genres,
  original_language = excluded.original_language,
  country = excluded.country,
  release_date = excluded.release_date,
  release_year = excluded.release_year,
  poster_url = excluded.poster_url,
  backdrop_url = excluded.backdrop_url,
  trailer_url = excluded.trailer_url,
  duration_minutes = excluded.duration_minutes,
  episodes = excluded.episodes,
  season_number = excluded.season_number,
  studio = excluded.studio,
  network = excluded.network,
  director = excluded.director,
  cast = excluded.cast,
  characters = excluded.characters,
  rating_average = excluded.rating_average,
  rating_count = excluded.rating_count,
  imdb_rating = excluded.imdb_rating,
  mal_rating = excluded.mal_rating,
  popularity_score = excluded.popularity_score,
  ai_summary = excluded.ai_summary,
  ai_tags = excluded.ai_tags,
  themes = excluded.themes,
  moods = excluded.moods,
  is_active = true;

commit;
