-- NexaPlay AI Batch 3: additive AI intelligence and behavior foundation.
-- Batch 1 contents and Batch 2A character tables are intentionally unchanged.

begin;

create schema if not exists extensions;
create extension if not exists vector with schema extensions;

create table if not exists public.content_embeddings (
  id bigint generated by default as identity primary key,
  content_id bigint not null references public.contents(id) on delete cascade,
  embedding extensions.vector(384) not null,
  model text not null,
  search_document text not null,
  document_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint content_embeddings_content_model_key unique (content_id, model),
  constraint content_embeddings_model_not_blank check (btrim(model) <> ''),
  constraint content_embeddings_document_not_blank check (btrim(search_document) <> ''),
  constraint content_embeddings_hash_format check (document_hash ~ '^[0-9a-f]{64}$')
);

create table if not exists public.user_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id bigint references public.contents(id) on delete cascade,
  interaction_type text not null,
  rating numeric(2, 1),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),

  constraint user_interactions_type_allowed check (
    interaction_type in ('view', 'like', 'watchlist', 'complete', 'rating', 'search')
  ),
  constraint user_interactions_rating_range check (rating is null or rating between 1 and 5),
  constraint user_interactions_rating_consistent check (
    (interaction_type = 'rating' and rating is not null)
    or (interaction_type <> 'rating' and rating is null)
  ),
  constraint user_interactions_content_consistent check (
    content_id is not null or interaction_type = 'search'
  ),
  constraint user_interactions_metadata_object check (jsonb_typeof(metadata) = 'object')
);

comment on table public.content_embeddings is
  'Versioned 384-dimensional semantic representations used by search, recommendations, and RAG.';
comment on column public.content_embeddings.id is 'Internal immutable embedding row identity.';
comment on column public.content_embeddings.content_id is 'Content represented by this embedding.';
comment on column public.content_embeddings.embedding is 'Normalized semantic vector emitted by the named model.';
comment on column public.content_embeddings.model is 'Sentence Transformer model identifier, allowing safe model migrations.';
comment on column public.content_embeddings.search_document is 'Exact normalized text embedded by the pipeline for audit and retrieval debugging.';
comment on column public.content_embeddings.document_hash is 'SHA-256 of search_document used to skip unchanged records and resume jobs.';
comment on column public.content_embeddings.created_at is 'Timestamp of the first embedding for this content/model pair.';
comment on column public.content_embeddings.updated_at is 'Timestamp of the most recent successful regeneration.';

comment on table public.user_interactions is
  'Append-only behavior events that form the foundation for personalized recommendations.';
comment on column public.user_interactions.id is 'Internal immutable interaction identity.';
comment on column public.user_interactions.user_id is 'Supabase Auth user who generated the event.';
comment on column public.user_interactions.content_id is 'Related catalog content; nullable only for search events.';
comment on column public.user_interactions.interaction_type is 'One of view, like, watchlist, complete, rating, or search.';
comment on column public.user_interactions.rating is 'One-to-five score, required only for rating events.';
comment on column public.user_interactions.metadata is 'Non-sensitive event context such as a search query or UI source.';
comment on column public.user_interactions.created_at is 'UTC-aware event timestamp.';

create index if not exists content_embeddings_content_idx
  on public.content_embeddings (content_id);
create index if not exists content_embeddings_model_idx
  on public.content_embeddings (model);
create index if not exists content_embeddings_hnsw_idx
  on public.content_embeddings using hnsw (embedding extensions.vector_cosine_ops);
create index if not exists user_interactions_user_created_idx
  on public.user_interactions (user_id, created_at desc);
create index if not exists user_interactions_content_type_idx
  on public.user_interactions (content_id, interaction_type);
create index if not exists user_interactions_type_created_idx
  on public.user_interactions (interaction_type, created_at desc);

create or replace function public.set_content_embedding_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists content_embeddings_set_updated_at on public.content_embeddings;
create trigger content_embeddings_set_updated_at
before update on public.content_embeddings
for each row execute function public.set_content_embedding_updated_at();

create or replace function public.match_content_embeddings(
  query_embedding extensions.vector(384),
  match_count integer default 10,
  match_model text default 'sentence-transformers/all-MiniLM-L6-v2',
  filter_content_type text default null,
  min_similarity double precision default 0
)
returns table (
  content_id bigint,
  title text,
  content_type text,
  overview text,
  genres jsonb,
  themes jsonb,
  moods jsonb,
  keywords jsonb,
  poster_url text,
  rating_average numeric,
  rating_count integer,
  popularity_score numeric,
  characters jsonb,
  similarity double precision
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    c.id,
    c.title,
    c.content_type,
    c.overview,
    c.genres,
    c.themes,
    c.moods,
    c.keywords,
    c.poster_url,
    c.rating_average,
    c.rating_count,
    c.popularity_score,
    coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'name', ch.name,
          'description', ch.description,
          'role', cc.role,
          'actor_name', cc.actor_name,
          'voice_actor', cc.voice_actor
        ) order by cc.importance_score desc, ch.name
      )
      from public.content_characters cc
      join public.characters ch on ch.id = cc.character_id
      where cc.content_id = c.id
    ), '[]'::jsonb),
    1 - (ce.embedding operator(extensions.<=>) query_embedding)
  from public.content_embeddings ce
  join public.contents c on c.id = ce.content_id
  where c.is_active = true
    and ce.model = match_model
    and (filter_content_type is null or c.content_type = filter_content_type)
    and 1 - (ce.embedding operator(extensions.<=>) query_embedding) >= coalesce(min_similarity, 0)
  order by ce.embedding operator(extensions.<=>) query_embedding
  limit least(greatest(coalesce(match_count, 10), 1), 100);
$$;

comment on function public.match_content_embeddings(extensions.vector, integer, text, text, double precision) is
  'Server-side cosine retrieval over versioned embeddings with grounded content and character metadata.';

alter table public.content_embeddings enable row level security;
alter table public.user_interactions enable row level security;

create policy content_embeddings_authenticated_read
on public.content_embeddings for select to authenticated
using (true);

create policy content_embeddings_admin_write
on public.content_embeddings for all to authenticated
using ((select public.is_catalog_admin()))
with check ((select public.is_catalog_admin()));

create policy user_interactions_read_own
on public.user_interactions for select to authenticated
using ((select auth.uid()) = user_id);

create policy user_interactions_insert_own
on public.user_interactions for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy user_interactions_delete_own
on public.user_interactions for delete to authenticated
using ((select auth.uid()) = user_id);

grant select on table public.content_embeddings to authenticated;
grant select, insert, delete on table public.user_interactions to authenticated;
grant all on table public.content_embeddings, public.user_interactions to service_role;
grant usage, select on sequence public.content_embeddings_id_seq, public.user_interactions_id_seq
  to authenticated, service_role;
revoke execute on function public.set_content_embedding_updated_at() from public, anon, authenticated;
revoke execute on function public.match_content_embeddings(
  extensions.vector, integer, text, text, double precision
) from public, anon, authenticated;
grant execute on function public.match_content_embeddings(
  extensions.vector, integer, text, text, double precision
) to service_role;

commit;
