-- NexaPlay Batch 3: authenticated personalization, explicit ratings/favorites,
-- derived taste profiles, and external user preference embeddings.

begin;

create schema if not exists extensions;
create extension if not exists vector with schema extensions;

create table public.user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  favorite_genres jsonb not null default '[]'::jsonb,
  favorite_types jsonb not null default '[]'::jsonb,
  favorite_moods jsonb not null default '[]'::jsonb,
  disliked_genres jsonb not null default '[]'::jsonb,
  onboarding_completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_preferences_genres_array check (jsonb_typeof(favorite_genres) = 'array'),
  constraint user_preferences_types_array check (jsonb_typeof(favorite_types) = 'array'),
  constraint user_preferences_moods_array check (jsonb_typeof(favorite_moods) = 'array'),
  constraint user_preferences_disliked_array check (jsonb_typeof(disliked_genres) = 'array'),
  constraint user_preferences_onboarding_genres check (
    not onboarding_completed or jsonb_array_length(favorite_genres) >= 3
  )
);

create table public.ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id bigint not null references public.contents(id) on delete cascade,
  rating numeric(2, 1) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ratings_user_content_key unique (user_id, content_id),
  constraint ratings_value_range check (rating between 1 and 5)
);

create table public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content_id bigint not null references public.contents(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint favorites_user_content_key unique (user_id, content_id)
);

create table public.user_taste_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  genre_scores jsonb not null default '{}'::jsonb,
  styles jsonb not null default '[]'::jsonb,
  source_summary jsonb not null default '{}'::jsonb,
  profile_version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_taste_profiles_genres_object check (jsonb_typeof(genre_scores) = 'object'),
  constraint user_taste_profiles_styles_array check (jsonb_typeof(styles) = 'array'),
  constraint user_taste_profiles_summary_object check (jsonb_typeof(source_summary) = 'object')
);

create table public.user_embeddings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  embedding extensions.vector(384),
  model text not null default 'sentence-transformers/all-MiniLM-L6-v2',
  source_hash text,
  status text not null default 'pending',
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_embeddings_status_allowed check (status in ('pending', 'completed', 'failed')),
  constraint user_embeddings_hash_format check (source_hash is null or source_hash ~ '^[0-9a-f]{64}$')
);

alter table public.watch_history
  add column if not exists completed boolean not null default false,
  add column if not exists last_watched timestamptz not null default now();

update public.watch_history
set completed = status = 'completed' or progress >= 100,
    last_watched = coalesce(updated_at, watched_at, now());

create index ratings_user_updated_idx on public.ratings (user_id, updated_at desc);
create index ratings_content_idx on public.ratings (content_id);
create index favorites_user_created_idx on public.favorites (user_id, created_at desc);
create index favorites_content_idx on public.favorites (content_id);
create index user_embeddings_status_idx on public.user_embeddings (status, updated_at);
create index watch_history_user_last_watched_idx
  on public.watch_history (user_id, last_watched desc);

comment on table public.user_preferences is 'Explicit onboarding and editable recommendation preferences.';
comment on table public.ratings is 'Canonical one-to-five user rating with one row per user/content.';
comment on table public.favorites is 'Explicit favorite content distinct from the watchlist.';
comment on table public.user_taste_profiles is 'Derived, explainable user taste weights and storytelling styles.';
comment on table public.user_embeddings is '384-dimensional preference vector generated only by the external embedding service.';

create trigger user_preferences_set_updated_at before update on public.user_preferences
for each row execute function public.set_application_updated_at();
create trigger ratings_set_updated_at before update on public.ratings
for each row execute function public.set_application_updated_at();
create trigger user_taste_profiles_set_updated_at before update on public.user_taste_profiles
for each row execute function public.set_application_updated_at();
create trigger user_embeddings_set_updated_at before update on public.user_embeddings
for each row execute function public.set_application_updated_at();

create or replace function public.sync_watch_history_personalization()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.completed := new.completed or new.status = 'completed' or new.progress >= 100;
  if new.completed then
    new.status := 'completed';
    new.progress := greatest(new.progress, 100);
  end if;
  new.last_watched := now();
  return new;
end;
$$;

drop trigger if exists watch_history_sync_personalization on public.watch_history;
create trigger watch_history_sync_personalization
before insert or update of progress, status, completed on public.watch_history
for each row execute function public.sync_watch_history_personalization();

alter table public.user_preferences enable row level security;
alter table public.ratings enable row level security;
alter table public.favorites enable row level security;
alter table public.user_taste_profiles enable row level security;
alter table public.user_embeddings enable row level security;

create policy user_preferences_own_all on public.user_preferences
for all to authenticated using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy ratings_own_all on public.ratings
for all to authenticated using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy favorites_own_all on public.favorites
for all to authenticated using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy user_taste_profiles_own_all on public.user_taste_profiles
for all to authenticated using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
create policy user_embeddings_own_all on public.user_embeddings
for all to authenticated using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

grant select, insert, update, delete on
  public.user_preferences,
  public.ratings,
  public.favorites,
  public.user_taste_profiles,
  public.user_embeddings
to authenticated;
grant all on
  public.user_preferences,
  public.ratings,
  public.favorites,
  public.user_taste_profiles,
  public.user_embeddings
to service_role;
grant usage, select on sequence public.ratings_id_seq, public.favorites_id_seq
to authenticated, service_role;
revoke execute on function public.sync_watch_history_personalization()
from public, anon, authenticated;

commit;
