-- NexaPlay AI Batch 5: production operations, admin analytics, and automation.
-- Additive only: recommendation weights, AI models, and ingestion tables are unchanged.

begin;

create table if not exists public.recommendation_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  strategy text not null,
  result_count integer not null default 0,
  average_score numeric(8, 6),
  created_at timestamptz not null default now(),
  constraint recommendation_requests_strategy_not_blank check (btrim(strategy) <> ''),
  constraint recommendation_requests_result_count_nonnegative check (result_count >= 0)
);

create table if not exists public.service_health_checks (
  id bigint generated by default as identity primary key,
  service_name text not null,
  status text not null,
  latency_ms integer,
  details jsonb not null default '{}'::jsonb,
  checked_at timestamptz not null default now(),
  constraint service_health_name_not_blank check (btrim(service_name) <> ''),
  constraint service_health_status_allowed check (status in ('healthy', 'degraded', 'down')),
  constraint service_health_latency_nonnegative check (latency_ms is null or latency_ms >= 0)
);

create table if not exists public.admin_job_runs (
  id bigint generated by default as identity primary key,
  job_name text not null,
  status text not null default 'running',
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  duration_ms bigint,
  metrics jsonb not null default '{}'::jsonb,
  error_type text,
  error_message text,
  constraint admin_job_name_not_blank check (btrim(job_name) <> ''),
  constraint admin_job_status_allowed check (status in ('running', 'succeeded', 'failed', 'skipped')),
  constraint admin_job_duration_nonnegative check (duration_ms is null or duration_ms >= 0)
);

create table if not exists public.analytics_daily (
  metric_date date primary key,
  total_users bigint not null default 0,
  active_users bigint not null default 0,
  new_users bigint not null default 0,
  watch_minutes numeric(16, 2) not null default 0,
  recommendation_requests bigint not null default 0,
  recommendation_clicks bigint not null default 0,
  recommendation_ctr numeric(8, 4) not null default 0,
  snapshot jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists recommendation_requests_created_idx
  on public.recommendation_requests (created_at desc);
create index if not exists recommendation_requests_user_idx
  on public.recommendation_requests (user_id, created_at desc);
create index if not exists service_health_service_checked_idx
  on public.service_health_checks (service_name, checked_at desc);
create index if not exists admin_job_runs_name_started_idx
  on public.admin_job_runs (job_name, started_at desc);
create index if not exists admin_job_runs_status_idx
  on public.admin_job_runs (status, started_at desc);

comment on table public.recommendation_requests is 'One aggregate event per recommendation response; no prompts or private conversation content are stored.';
comment on table public.service_health_checks is 'Historical dependency health samples used by the protected operations dashboard.';
comment on table public.admin_job_runs is 'Auditable scheduler and worker execution history with sanitized errors.';
comment on table public.analytics_daily is 'Daily production metrics materialized by the Batch 5 worker.';

alter table public.recommendation_requests enable row level security;
alter table public.service_health_checks enable row level security;
alter table public.admin_job_runs enable row level security;
alter table public.analytics_daily enable row level security;

create policy recommendation_requests_admin_read on public.recommendation_requests
for select to authenticated using ((select public.is_catalog_admin()));
create policy service_health_admin_read on public.service_health_checks
for select to authenticated using ((select public.is_catalog_admin()));
create policy admin_job_runs_admin_read on public.admin_job_runs
for select to authenticated using ((select public.is_catalog_admin()));
create policy analytics_daily_admin_read on public.analytics_daily
for select to authenticated using ((select public.is_catalog_admin()));

grant select on public.recommendation_requests, public.service_health_checks,
  public.admin_job_runs, public.analytics_daily to authenticated;
grant all on public.recommendation_requests, public.service_health_checks,
  public.admin_job_runs, public.analytics_daily to service_role;
grant usage, select on sequence public.recommendation_requests_id_seq,
  public.service_health_checks_id_seq, public.admin_job_runs_id_seq to service_role;

create or replace function public.record_recommendation_request(
  p_strategy text,
  p_result_count integer,
  p_average_score numeric default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if btrim(coalesce(p_strategy, '')) = '' then
    raise exception 'strategy is required';
  end if;
  insert into public.recommendation_requests (user_id, strategy, result_count, average_score)
  values (auth.uid(), left(p_strategy, 80), greatest(coalesce(p_result_count, 0), 0), p_average_score);
end;
$$;

create or replace function public.record_service_health(
  p_service_name text,
  p_status text,
  p_latency_ms integer,
  p_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_catalog_admin() then
    raise exception 'admin access required' using errcode = '42501';
  end if;
  insert into public.service_health_checks (service_name, status, latency_ms, details)
  values (left(p_service_name, 80), p_status, greatest(p_latency_ms, 0), coalesce(p_details, '{}'::jsonb));
end;
$$;

create or replace function public.get_admin_dashboard()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  payload jsonb;
begin
  if not public.is_catalog_admin() then
    raise exception 'admin access required' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'summary', jsonb_build_object(
      'totalUsers', (select count(*) from auth.users),
      'totalContents', (select count(*) from public.contents),
      'movies', (select count(*) from public.contents where content_type::text = 'movie'),
      'series', (select count(*) from public.contents where content_type::text in ('series', 'tv_series', 'kdrama')),
      'anime', (select count(*) from public.contents where content_type::text = 'anime'),
      'ratings', (select count(*) from public.ratings),
      'watchActivity', (select count(*) from public.watch_history where last_watched >= now() - interval '30 days')
    ),
    'content', jsonb_build_object(
      'mostWatched', coalesce((
        select jsonb_agg(row_data order by watch_count desc) from (
          select c.id, c.title, count(*) as watch_count
          from public.watch_history wh join public.contents c on c.id = wh.content_id
          group by c.id, c.title order by watch_count desc limit 8
        ) row_data
      ), '[]'::jsonb),
      'highestRated', coalesce((
        select jsonb_agg(row_data order by average_rating desc) from (
          select c.id, c.title, round(avg(r.rating), 2) as average_rating, count(*) as rating_count
          from public.ratings r join public.contents c on c.id = r.content_id
          group by c.id, c.title having count(*) > 0 order by average_rating desc, rating_count desc limit 8
        ) row_data
      ), '[]'::jsonb),
      'trendingGenres', coalesce((
        select jsonb_agg(row_data order by activity desc) from (
          select genre, count(*) as activity
          from public.watch_history wh join public.contents c on c.id = wh.content_id
          cross join lateral jsonb_array_elements_text(c.genres) genre
          where wh.last_watched >= now() - interval '30 days'
          group by genre order by activity desc limit 8
        ) row_data
      ), '[]'::jsonb),
      'missingMetadata', (select count(*) from public.contents where overview is null or btrim(overview) = '' or poster_url is null),
      'missingEmbeddings', (select count(*) from public.contents c where not exists (select 1 from public.content_embeddings ce where ce.content_id = c.id))
    ),
    'users', jsonb_build_object(
      'total', (select count(*) from auth.users),
      'active30d', (select count(distinct user_id) from public.user_interactions where created_at >= now() - interval '30 days'),
      'new30d', (select count(*) from auth.users where created_at >= now() - interval '30 days'),
      'retentionPercent', coalesce((
        select round(100.0 * count(distinct recent.user_id) / nullif(count(distinct previous.user_id), 0), 2)
        from public.user_interactions previous
        left join public.user_interactions recent on recent.user_id = previous.user_id
          and recent.created_at >= now() - interval '7 days'
        where previous.created_at >= now() - interval '14 days'
          and previous.created_at < now() - interval '7 days'
      ), 0),
      'averageRating', coalesce((select round(avg(rating), 2) from public.ratings), 0),
      'watchMinutes', coalesce((select round(sum(coalesce(c.duration_minutes, 0) * wh.progress / 100.0), 2) from public.watch_history wh join public.contents c on c.id = wh.content_id), 0)
    ),
    'recommendations', jsonb_build_object(
      'generated', (select count(*) from public.recommendation_requests),
      'resultsServed', (select coalesce(sum(result_count), 0) from public.recommendation_requests),
      'clicks', (select count(*) from public.user_interactions where interaction_type = 'click' and metadata ->> 'source' = 'recommendation'),
      'views', (select count(*) from public.user_interactions where interaction_type = 'view'),
      'ratings', (select count(*) from public.user_interactions where interaction_type = 'rating'),
      'ctr', coalesce((select round(100.0 * (select count(*) from public.user_interactions where interaction_type = 'click' and metadata ->> 'source' = 'recommendation') / nullif(sum(result_count), 0), 2) from public.recommendation_requests), 0),
      'averageScore', coalesce((select round(avg(average_score), 4) from public.recommendation_requests), 0)
    ),
    'jobs', coalesce((select jsonb_agg(row_data order by started_at desc) from (
      select id, job_name, status, started_at, finished_at, duration_ms, metrics, error_type
      from public.admin_job_runs order by started_at desc limit 12
    ) row_data), '[]'::jsonb),
    'services', coalesce((select jsonb_agg(row_data order by service_name) from (
      select distinct on (service_name) service_name, status, latency_ms, checked_at, details
      from public.service_health_checks order by service_name, checked_at desc
    ) row_data), '[]'::jsonb),
    'generatedAt', now()
  ) into payload;
  return payload;
end;
$$;

create or replace function public.refresh_daily_analytics()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  if auth.role() <> 'service_role' and not public.is_catalog_admin() then
    raise exception 'trusted worker access required' using errcode = '42501';
  end if;
  insert into public.analytics_daily (
    metric_date, total_users, active_users, new_users, watch_minutes,
    recommendation_requests, recommendation_clicks, recommendation_ctr, snapshot, updated_at
  )
  select
    current_date,
    (select count(*) from auth.users),
    (select count(distinct user_id) from public.user_interactions where created_at >= current_date),
    (select count(*) from auth.users where created_at >= current_date),
    coalesce((select sum(coalesce(c.duration_minutes, 0) * wh.progress / 100.0) from public.watch_history wh join public.contents c on c.id = wh.content_id where wh.last_watched >= current_date), 0),
    (select count(*) from public.recommendation_requests where created_at >= current_date),
    (select count(*) from public.user_interactions where interaction_type = 'click' and metadata ->> 'source' = 'recommendation' and created_at >= current_date),
    coalesce((select round(100.0 * (select count(*) from public.user_interactions where interaction_type = 'click' and metadata ->> 'source' = 'recommendation' and created_at >= current_date) / nullif(sum(result_count), 0), 4) from public.recommendation_requests where created_at >= current_date), 0),
    jsonb_build_object('refreshedAt', now()),
    now()
  on conflict (metric_date) do update set
    total_users = excluded.total_users, active_users = excluded.active_users,
    new_users = excluded.new_users, watch_minutes = excluded.watch_minutes,
    recommendation_requests = excluded.recommendation_requests,
    recommendation_clicks = excluded.recommendation_clicks,
    recommendation_ctr = excluded.recommendation_ctr,
    snapshot = excluded.snapshot, updated_at = now();
  select to_jsonb(a) into result from public.analytics_daily a where metric_date = current_date;
  return result;
end;
$$;

create or replace function public.cleanup_operational_history()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  removed_health bigint;
  removed_jobs bigint;
begin
  if auth.role() <> 'service_role' then
    raise exception 'service role required' using errcode = '42501';
  end if;
  delete from public.service_health_checks where checked_at < now() - interval '90 days';
  get diagnostics removed_health = row_count;
  delete from public.admin_job_runs where started_at < now() - interval '180 days';
  get diagnostics removed_jobs = row_count;
  return jsonb_build_object('healthChecksRemoved', removed_health, 'jobRunsRemoved', removed_jobs);
end;
$$;

revoke execute on function public.record_recommendation_request(text, integer, numeric) from public;
grant execute on function public.record_recommendation_request(text, integer, numeric) to anon, authenticated, service_role;
revoke execute on function public.record_service_health(text, text, integer, jsonb) from public, anon;
grant execute on function public.record_service_health(text, text, integer, jsonb) to authenticated, service_role;
revoke execute on function public.get_admin_dashboard() from public, anon;
grant execute on function public.get_admin_dashboard() to authenticated, service_role;
revoke execute on function public.refresh_daily_analytics() from public, anon, authenticated;
grant execute on function public.refresh_daily_analytics() to service_role;
revoke execute on function public.cleanup_operational_history() from public, anon, authenticated;
grant execute on function public.cleanup_operational_history() to service_role;

commit;
