-- NexaPlay AI Batch 2A: normalized character knowledge layer.
-- This migration is additive and intentionally leaves public.contents unchanged.

begin;

create table if not exists public.characters (
  id bigint generated by default as identity primary key,
  name text not null,
  normalized_name text not null,
  alternative_names jsonb not null default '[]'::jsonb,
  description text,
  image_url text,
  source text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint characters_normalized_name_key unique (normalized_name),
  constraint characters_name_not_blank check (btrim(name) <> ''),
  constraint characters_normalized_name_not_blank check (btrim(normalized_name) <> ''),
  constraint characters_normalized_name_canonical check (
    normalized_name = lower(regexp_replace(btrim(name), '[[:space:]]+', ' ', 'g'))
  ),
  constraint characters_alternative_names_array check (
    jsonb_typeof(alternative_names) = 'array'
  ),
  constraint characters_source_not_blank check (btrim(source) <> ''),
  constraint characters_source_canonical_case check (source = upper(source))
);

create table if not exists public.content_characters (
  id bigint generated by default as identity primary key,
  content_id bigint not null references public.contents(id) on delete cascade,
  character_id bigint not null references public.characters(id) on delete cascade,
  role text not null default 'supporting',
  actor_name text,
  voice_actor text,
  importance_score integer not null default 0,
  source text not null,
  created_at timestamptz not null default now(),

  constraint content_characters_identity_key unique nulls not distinct (
    content_id,
    character_id,
    actor_name,
    voice_actor,
    source
  ),
  constraint content_characters_role_allowed check (
    role in ('main', 'supporting', 'background', 'other')
  ),
  constraint content_characters_actor_not_blank check (
    actor_name is null or btrim(actor_name) <> ''
  ),
  constraint content_characters_voice_actor_not_blank check (
    voice_actor is null or btrim(voice_actor) <> ''
  ),
  constraint content_characters_importance_range check (
    importance_score between 0 and 100
  ),
  constraint content_characters_source_not_blank check (btrim(source) <> ''),
  constraint content_characters_source_canonical_case check (source = upper(source))
);

comment on table public.characters is
  'Deduplicated fictional character entities used by discovery, recommendation, semantic search, and future RAG enrichment.';
comment on column public.characters.id is 'Internal immutable character identity.';
comment on column public.characters.name is 'Canonical display name for the fictional character.';
comment on column public.characters.normalized_name is 'Case-insensitive, whitespace-normalized natural key used for deduplication.';
comment on column public.characters.alternative_names is 'JSON array of aliases, localized names, and source-specific character names.';
comment on column public.characters.description is 'Provider-supplied character description; AI enrichment is intentionally excluded from Batch 2A.';
comment on column public.characters.image_url is 'Canonical character portrait URL when supplied by the provider.';
comment on column public.characters.source is 'Uppercase provider that supplied the canonical character record.';
comment on column public.characters.created_at is 'UTC-aware creation timestamp.';
comment on column public.characters.updated_at is 'UTC-aware timestamp refreshed whenever the character record changes.';

comment on table public.content_characters is
  'Many-to-many appearances connecting contents to characters, performers, voice actors, roles, and importance.';
comment on column public.content_characters.id is 'Internal immutable appearance relationship identity.';
comment on column public.content_characters.content_id is 'Referenced content in the existing unified catalog.';
comment on column public.content_characters.character_id is 'Referenced deduplicated fictional character.';
comment on column public.content_characters.role is 'Normalized narrative role: main, supporting, background, or other.';
comment on column public.content_characters.actor_name is 'On-screen performer name for live-action content.';
comment on column public.content_characters.voice_actor is 'Voice performer name for animated content.';
comment on column public.content_characters.importance_score is 'Provider-derived importance from 0 to 100 for ranking appearances.';
comment on column public.content_characters.source is 'Uppercase provider that supplied this appearance relationship.';
comment on column public.content_characters.created_at is 'UTC-aware relationship creation timestamp.';

create index if not exists characters_name_trgm_idx
  on public.characters using gin (name extensions.gin_trgm_ops);
create index if not exists characters_source_idx
  on public.characters (source);
create index if not exists characters_alternative_names_gin_idx
  on public.characters using gin (alternative_names jsonb_path_ops);
create index if not exists content_characters_content_idx
  on public.content_characters (content_id, importance_score desc);
create index if not exists content_characters_character_idx
  on public.content_characters (character_id);
create index if not exists content_characters_role_idx
  on public.content_characters (role);

create or replace function public.set_character_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

comment on function public.set_character_updated_at() is
  'Refreshes characters.updated_at before a row update.';

drop trigger if exists characters_set_updated_at on public.characters;
create trigger characters_set_updated_at
before update on public.characters
for each row
execute function public.set_character_updated_at();

alter table public.characters enable row level security;
alter table public.content_characters enable row level security;

create policy characters_anon_read_active_content
on public.characters
for select
to anon
using (
  exists (
    select 1
    from public.content_characters as cc
    join public.contents as c on c.id = cc.content_id
    where cc.character_id = characters.id
      and c.is_active = true
  )
);

create policy characters_authenticated_read
on public.characters
for select
to authenticated
using (true);

create policy characters_admin_write
on public.characters
for all
to authenticated
using ((select public.is_catalog_admin()))
with check ((select public.is_catalog_admin()));

create policy content_characters_anon_read_active_content
on public.content_characters
for select
to anon
using (
  exists (
    select 1
    from public.contents as c
    where c.id = content_characters.content_id
      and c.is_active = true
  )
);

create policy content_characters_authenticated_read
on public.content_characters
for select
to authenticated
using (true);

create policy content_characters_admin_write
on public.content_characters
for all
to authenticated
using ((select public.is_catalog_admin()))
with check ((select public.is_catalog_admin()));

comment on policy characters_anon_read_active_content on public.characters is
  'Anonymous clients can read characters that appear in active catalog content.';
comment on policy characters_authenticated_read on public.characters is
  'Authenticated clients can read all character entities.';
comment on policy characters_admin_write on public.characters is
  'Only catalog admins can write through user-scoped Supabase clients.';
comment on policy content_characters_anon_read_active_content on public.content_characters is
  'Anonymous clients can read relationships for active catalog content.';
comment on policy content_characters_authenticated_read on public.content_characters is
  'Authenticated clients can read every character relationship.';
comment on policy content_characters_admin_write on public.content_characters is
  'Only catalog admins can write through user-scoped Supabase clients.';

grant select on table public.characters, public.content_characters to anon;
grant select, insert, update, delete on table public.characters, public.content_characters to authenticated;
grant all on table public.characters, public.content_characters to service_role;
grant usage, select on sequence public.characters_id_seq, public.content_characters_id_seq
  to authenticated, service_role;
revoke execute on function public.set_character_updated_at() from public, anon, authenticated;

commit;
